### ISSUE TITLE
NetAistransponder 

### ISSUE THREAD

**Issue by MikeyJ4** [VladimirKalachikhin/netAIS#2]
Is it possible to create a internet ais transponder

**Comment by VladimirKalachikhin** [comment]
What is a "transponder"?

**Comment by mikeshedrack** [comment]
Well it's a device used for sharing and receiving ais signals

**Comment by VladimirKalachikhin** [comment]
In that volume, I know. What do you understand by "internet ais transponder"?

**Comment by mikeshedrack** [comment]
An app sharing and receiving signals using internet

**Comment by VladimirKalachikhin** [comment]
netAIS?

**Comment by mikeshedrack** [comment]
Can it be able to create a new vessel just like boat beacon app

**Comment by VladimirKalachikhin** [comment]
read the docs

**Comment by mikeshedrack** [comment]
Brother, please can it be able to share database with marinetraffic

**Comment by VladimirKalachikhin** [comment]
Dude, why is this necessary?

**Comment by mikeshedrack** [comment]
Let's talk privately 
mikeshedrack88@gmail.com

**Comment by mikeshedrack** [comment]
Why it's necessary because am trying to create an app that will serve as a ais transponder though am doing it for mine school project

**Comment by mikeshedrack** [comment]
send me your whatsapp number via mikeshedrack88@gmail.com  Let me call you 
I appreciate
